//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevScope.CascadeLookup.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CascadeLookupResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CascadeLookupResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevScope.CascadeLookup.Resources.CascadeLookupResources", typeof(CascadeLookupResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo:.
        /// </summary>
        internal static string ConfigCascadeModeLabel {
            get {
                return ResourceManager.GetString("ConfigCascadeModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        internal static string ConfigCascadeModeSaveButtonText {
            get {
                return ResourceManager.GetString("ConfigCascadeModeSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações Cascade Lookup.
        /// </summary>
        internal static string ConfigCascadeTitle {
            get {
                return ResourceManager.GetString("ConfigCascadeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coluna de relação:.
        /// </summary>
        internal static string EditorColumnLabel {
            get {
                return ResourceManager.GetString("EditorColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem dependências?.
        /// </summary>
        internal static string EditorDependenciesLabel {
            get {
                return ResourceManager.GetString("EditorDependenciesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coluna dependente da lista de relação:.
        /// </summary>
        internal static string EditorDependencyColumnLabel {
            get {
                return ResourceManager.GetString("EditorDependencyColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coluna dependente desta lista:.
        /// </summary>
        internal static string EditorDependencyListColumnLabel {
            get {
                return ResourceManager.GetString("EditorDependencyListColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Selecione um item).
        /// </summary>
        internal static string EditorEmptyCascadeItem {
            get {
                return ResourceManager.GetString("EditorEmptyCascadeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na configuração do campo. Por favor contacte um administrador!.
        /// </summary>
        internal static string EditorErrorLabel {
            get {
                return ResourceManager.GetString("EditorErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de relação:.
        /// </summary>
        internal static string EditorListLabel {
            get {
                return ResourceManager.GetString("EditorListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é um campo obrigatório..
        /// </summary>
        internal static string EditorRequiredFieldMessage {
            get {
                return ResourceManager.GetString("EditorRequiredFieldMessage", resourceCulture);
            }
        }
    }
}
